name: npm-audit                                  

on:
  push:
    branches:                                 
      - main
  workflow_dispatch:

jobs:


  oast_npm_audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      
      - run: npm install
      - run: npm audit --json | tee npm_audit_report.json

      - uses: actions/upload-artifact@v2
        with:
          name: nmp_audit
          path: npm_audit_report.json
