name: npm-audit                                  

on:
  push:
    branches:                                 
      - main
  workflow_dispatch:

jobs:


  npm_audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.1.0
        with:
          node-version: '18'
      
      - run: npm install ./splunk-elb-classic-access-logs-processor
      - run: npm audit --json | tee npm_audit_report.json
      - run: npm explain tough-cookie
      - run: npm ls tough-cookie
      - run: npm ll tough-cookie
      - run: npm la tough-cookie

      - uses: actions/upload-artifact@v4
        with:
          name: nmp_audit
          path: npm_audit_report.json
